## ADUXX-ZGLOSZENIA

usage: "&cU≈ºycie: /zglos <nick>"
info-usage: "&2U≈ºycie: /zglosinfo <nick>"

not-found-player: "&cGracz [PLAYER] nie zosta≈Ç znaleziony!"
report-title: "&aZg≈Çosi≈Çe≈õ gracza: &2[PLAYER]"
admin-report-msg: "&6Nowe zg≈Çoszenie. &fGracz &e[PLAYER] &fzosta≈Ç zg≈Çoszony za: &c[REASON]"
config-reload: "&aPrze≈Çadowano config!"
no-permission-reload: "&7Nie masz &cpermisji!"
player-reported: "&4Zg≈Çosi≈Çe≈õ gracza [PLAYER] , je≈õli zostanie zbanowany dostaniesz powiadomienie"
self-report: "&cNie mo≈ºesz zg≈Çosiƒá samego siebie..."
cooldown: 230 #czas podaje siƒô w sekundach
cooldown-message: "&7Posiadasz &ccooldown! &7Spr√≥b√≥j &cponownie &7za &c[COOLDOWN] &7sekund"
bossBarFormat: "&cGracz kt√≥rego zg≈Çosi≈Çes otzyma≈Ç bana!"
bossBarColor: RED
bossBarStyle: SOLID
bossBarDuration: 15 # w sekundach

permission: "zgloszenia.admin" #permisja do otrzymywania zg≈Çosze≈Ñ
block-report-permission: "zgloszenia.bypass" #gracz , kt√≥ry posiada tƒÖ permisje nie mo≈ºe zostaƒá zgloszony
config-reload-permission: "zgloszenia.reload" #premisja do prze≈Çadowywania config.yml
cannot-report: "&cTego gracza nie mo≈ºna zg≈Çosiƒá!"
report-list-permission: "zgloszenia.show" #permisja do listy zg≈Çosze≈Ñ
report-list-messages:
  - "&8‚û§ &7Zg≈Çoszenie na &f[PLAYER]"
  - "&8‚û§ &7Ilo≈õƒá zg≈Çosze≈Ñ na gracza: &f[TIMES]"
  - "&8‚û§ &7Ostatnie zg≈Çoszenie [REASON]"

#discord webhook
webhook:
  url: ""
  color: "1807612"
  report-title: " "
  report-description: "**üöÄGracz [REPORTER] Zg≈Çosi≈Ç gracza: [PLAYER] , pow√≥d: [REASON]**"
  report-footer: "System zg≈Çosze≈Ñ: dc.lemonhost.pl"


gui:
  size: 45 #(od 9 do 54 slot√≥w)
  name: "&6&L Zg≈Ço≈õ gracza &f[PLAYER]"
  slots:
    0: {item: YELLOW_STAINED_GLASS_PANE, name: " ", lore: [" "]}
    1: {item: ORANGE_STAINED_GLASS_PANE, name: " ", lore: [" "]}
    2: {item: WHITE_STAINED_GLASS_PANE, name: " ", lore: [" "]}
    3: {item: WHITE_STAINED_GLASS_PANE, name: " ", lore: [" "]}
    5: {item: WHITE_STAINED_GLASS_PANE, name: " ", lore: [" "]}
    6: {item: WHITE_STAINED_GLASS_PANE, name: " ", lore: [" "]}
    7: {item: WHITE_STAINED_GLASS_PANE, name: " ", lore: [" "]}
    8: {item: ORANGE_STAINED_GLASS_PANE, name: " ", lore: [" "]}
    9: {item: YELLOW_STAINED_GLASS_PANE, name: " ", lore: [" "]}
    10: {item: ORANGE_STAINED_GLASS_PANE, name: " ", lore: [" "]}
    18: {item: ORANGE_STAINED_GLASS_PANE, name: " ", lore: [" "]}
    19: {item: WHITE_STAINED_GLASS_PANE, name: " ", lore: [" "]}
    21:
      item: DIAMOND_SWORD
      name: "&c&LKill Aura"
      lore:
        - ""
        - "&7Gracz korzysta ze wspomagaczy,kt√≥re"
        - "&7umo≈ºliwiajƒÖ mu bicie innych graczy dooko≈Ça siebie"
        - ""
        - "&cJe≈õli posiadasz nagranie stw√≥rz ticketa na &4discordzie"
        - ""
        - "&aKliknij,aby zg≈Çosiƒá"
    22:
      item: GOLDEN_SWORD
      name: "&e&LReach/Hitboxy"
      lore:
        - ""
        - "&7Gracz korzysta ze wspomagaczy,kt√≥re"
        - "&7umo≈ºliwiajƒÖ mu bicie z wiƒôkszej odleg≈Ço≈õci"
        - "&7lub powiƒôkszajƒÖcych hitbox innych graczy"
        - ""
        - "&cJe≈õli posiadasz nagranie stw√≥rz ticketa na &4discordzie"
        - ""
        - "&aKliknij,aby zg≈Çosiƒá"
    23:
      item: TOTEM_OF_UNDYING
      name: "&6&LAuto Totem"
      lore:
        - ""
        - "&7Gracz korzysta ze wspomagaczy,kt√≥re"
        - "&7umo≈ºliwiajƒÖ mu automatyczne zak≈Çadanie totem√≥w"
        - "&7lub zak≈Çadanie totemu za pomocƒÖ binda"
        - ""
        - "&cJe≈õli posiadasz nagranie stw√≥rz ticketa na &4discordzie"
        - ""
        - "&aKliknij,aby zg≈Çosiƒá"
    24:
      item: IRON_PICKAXE
      name: "&d&LFastbreaker/Nuker"
      lore:
        - ""
        - "&7Gracz korzysta ze wspomagaczy,kt√≥re"
        - "&7umo≈ºliwiajƒÖ mu szybsze kopanie blok√≥w"
        - ""
        - "&cJe≈õli posiadasz nagranie stw√≥rz ticketa na &4discordzie"
        - ""
        - "&aKliknij,aby zg≈Çosiƒá"
    25:
      item: COBWEB
      name: "&f&LBicie przez pajƒôczyny"
      lore:
        - ""
        - "&7Gracz korzysta ze wspomagaczy,kt√≥re"
        - "&7umo≈ºliwiajƒÖ mu bicie innych gracy przez pajƒôczyny"
        - ""
        - "&cJe≈õli posiadasz nagranie stw√≥rz ticketa na &4discordzie"
        - ""
        - "&aKliknij,aby zg≈Çosiƒá"
    27: {item: WHITE_STAINED_GLASS_PANE, name: " ", lore: [" "]}
    28: {item: ORANGE_STAINED_GLASS_PANE, name: " ", lore: [" "]}
    32:
      item: PHANTOM_MEMBRANE
      name: "&b&lInne"
      lore:
        - ""
        - "&7Gracz korzysta z innych nielegalnych wspomagaczy,"
        - "&7kt√≥re u≈ÇatwiajƒÖ mu rozgrywkƒô na serwerze"
        - ""
        - "&cJe≈õli posiadasz nagranie stw√≥rz ticketa na &4discordzie"
        - ""
        - "&aKliknij,aby zg≈Çosiƒá"
    36: {item: ORANGE_STAINED_GLASS_PANE, name: " ", lore: [" "]}
    37: {item: YELLOW_STAINED_GLASS_PANE, name: " ", lore: [" "]}
    38: {item: ORANGE_STAINED_GLASS_PANE, name: " ", lore: [" "]}
    39: {item: WHITE_STAINED_GLASS_PANE, name: " ", lore: [" "]}
    40: {item: WHITE_STAINED_GLASS_PANE, name: " ", lore: [" "]}
    42: {item: WHITE_STAINED_GLASS_PANE, name: " ", lore: [" "]}
    43: {item: WHITE_STAINED_GLASS_PANE, name: " ", lore: [" "]}
    44: {item: ORANGE_STAINED_GLASS_PANE, name: " ", lore: [" "]}
